### ISSUE TITLE
Buckshot roulette BRML not working. *bad title i know*

### ISSUE THREAD

**Issue by hellomynameisapistol** [AGO061/BuckshotRouletteModLoader#1]
Recently. delta patcher wants me to frick off. checksum validation off. latest version.  it says so "Error. cant run project. no main scene defined in the project. please help. with checksum validation its XDR3.

**Comment by AGO061** [comment]
Very odd, i haven't noticed anything odd while testing, i really wouldn't know how to help, have you installed any mods?

**Comment by NotHyper-474** [comment]
Just curiosity, are you trying to patch a pirated version?

**Comment by AGO061** [comment]
> Just curiosity, are you trying to patch a pirated version?

The mod loader relies on the build of the game being perfect but after bit, if there is anything that was changed in the binary (like trough piracy, though the game shouldn't have any checks) it wouldn't work. It could also be a simple corruption of the original file, flipping only one bit and messing something up

**Comment by NotHyper-474** [comment]
> > Just curiosity, are you trying to patch a pirated version?
> 
> The mod loader relies on the build of the game being perfect bit after bit, if there is anything that was changed in the binary (like trough piracy, though the game shouldn't have any checks) it wouldn't work. It could also be a simple corruption of the original file, flipping only one bit and messing something up

I'm asking because I tried to patch a version from SteamUnlocked but it only worked with one from IGG-Games, but I'm thinking there's a hotfix version that was released still named as v1.1 that some pirate websites don't have

**Comment by NotHyper-474** [comment]
Alright I did a SHA-256 test in the exe of both pirated versions and they're giving different hashes so they're definitely different.
One of them has a different folder name ("hotfix") so maybe there's indeed a hotfix version of v1.1

**Comment by starship17** [comment]
> > > not in error though just in exe
> > > Edit: Solved it. its working.
> > 
> > 
> > hey how did you solve it?
> 
> Basically, I double checked on yt, and since this lacks instruction to people that didnt see the video, I can say to get the modded version running after patch is in it (don't use checksum). Just make a folder called "Mods" (must be added manually which isn't a hassle), and it sits with the game, not the game in the mod folder, then just place the patch file with the game in folder (might be needed but better safe than sorry..). Run the game, and if you got mods like smarter ai then just put the zip in mods folder and that's it.
> 
> Apologies if there is some confusion on my text even though I am english. Typing it simple is not easy to do.

uhh it says something about missing since am i dumb or did i miss something

**Comment by vadmancs** [comment]
> > > > not in error though just in exe
> > > > Edit: Solved it. its working.
> > > 
> > > 
> > > hey how did you solve it?
> > 
> > 
> > Basically, I double checked on yt, and since this lacks instruction to people that didnt see the video, I can say to get the modded version running after patch is in it (don't use checksum). Just make a folder called "Mods" (must be added manually which isn't a hassle), and it sits with the game, not the game in the mod folder, then just place the patch file with the game in folder (might be needed but better safe than sorry..). Run the game, and if you got mods like smarter ai then just put the zip in mods folder and that's it.
> > Apologies if there is some confusion on my text even though I am english. Typing it simple is not easy to do.
> 
> uhh it says something about missing a main scene am i dumb or did i miss something

I got the same issue.

**Comment by AGO061** [comment]
guys using any cracked version of the game does not guarantee functionality (and i won't nor can provide it). It works on the original itch.io version because it is what delta patcher expects. one flipped bit could ruin the exe and make the game unplayable because delta patcher uses the .xdelta file to flip specific bits.

**Comment by AGO061** [comment]
> > > Just curiosity, are you trying to patch a pirated version?
> > 
> > The mod loader relies on the build of the game being perfect bit after bit, if there is anything that was changed in the binary (like trough piracy, though the game shouldn't have any checks) it wouldn't work. It could also be a simple corruption of the original file, flipping only one bit and messing something up
> 
> I'm asking because I tried to patch a version from SteamUnlocked but it only worked with one from IGG-Games, but I'm thinking it's not working 'couse there's a hotfix version that was released still named as v1.1 that some pirate websites don't have

also the mod loader only works with v1.1 of the game

**Comment by AGO061** [comment]
the itch.io version got no update as far as i can see so any weird versions you may find online aren't 100% original.

**Comment by NotHyper-474** [comment]
> > > > Just curiosity, are you trying to patch a pirated version?
> > > 
> > > The mod loader relies on the build of the game being perfect bit after bit, if there is anything that was changed in the binary (like trough piracy, though the game shouldn't have any checks) it wouldn't work. It could also be a simple corruption of the original file, flipping only one bit and messing something up
> > 
> > I'm asking because I tried to patch a version from SteamUnlocked but it only worked with one from IGG-Games, but I'm thinking it's not working 'couse there's a hotfix version that was released still named as v1.1 that some pirate websites don't have
> 
> also the mod loader only works with v1.1 of the game

exactly, both websites I downloaded it from showed it as v1.1, but one of them had the name "hotfix" (only the folder  had that name, in-game it still showed 1.1) and that's the one that worked

**Comment by AGO061** [comment]
> > > > > Just curiosity, are you trying to patch a pirated version?
> > > > 
> > > > The mod loader relies on the build of the game being perfect bit after bit, if there is anything that was changed in the binary (like trough piracy, though the game shouldn't have any checks) it wouldn't work. It could also be a simple corruption of the original file, flipping only one bit and messing something up
> > > 
> > > I'm asking because I tried to patch a version from SteamUnlocked but it only worked with one from IGG-Games, but I'm thinking it's not working 'couse there's a hotfix version that was released still named as v1.1 that some pirate websites don't have
> > 
> > also the mod loader only works with v1.1 of the game
> 
> exactly, both websites I downloaded it from showed it as v1.1, but one of them had the name "hotfix" (again, only the folder had that name, in-game it still showed 1.1) and that's the one that worked

probably some piracy sites change in part the binary so it returns a different checksum. It happens, and again i can't provide support for cracked executables because they are illegal so if that's the route someone wants to take (risks included) they'll have to figure it out on their own. I am happy to fix issues but can only do so for those that have a legitimate copy of the game.

**Comment by AGO061** [comment]
I think I'll close this issue now.
Basically don't use pirated versions of the game to install the mod loader if you want it to work.

**Comment by vadmancs** [comment]
Okay, I think I know what is the problem. When the 1.1 update got out I downloaded in a day or two (a legit copy from itch.io). The game says version 1.1 but when I tried to patch it, it says "An error has occurred: xdelta3: target window checksum mismatch: XD3_INVALID_INPUT". Now I downloaded again (a legit copy from itch.io) and try it again, and it worked. I double check it, both game says version 1.1, then I checked it with a hex editor (HxD) and found a lot of difference between the two executable.

**So the solution for this is just download it again.**

**Comment by NotHyper-474** [comment]
> probably some piracy sites change in part the binary so it returns a different checksum. It happens, and again i can't provide support for cracked executables because they are illegal so if that's the route someone wants to take (risks included) they'll have to figure it out on their own. I am happy to fix issues but can only do so for those that have a legitimate copy of the game.

That is fine by me.
Anyways I don't see why they would modify it (unless it's to hide a virus inside which I don't think was the case) and as someone said the fix was to download it again which suggests that the game was indeed updated but the developer didn't bother changing the version number, specially because it was probably just a small fix (hence the "hotfix" folder name)

Either way I managed to patch the game without errors so I don't really care about this anymore. Best of luck.

**Comment by AGO061** [comment]
probably there were 2 v1.1 versions so for now the fix is to download it again to ensure you have the correct 1.1 version if the game
