### ISSUE TITLE
The mods don't work for me, I read them in the game but they don't work

### ISSUE THREAD

**Issue by superrrrrr** [AGO061/BuckshotRouletteModLoader#11]
I have installed: TestMod - StarPanda-Challenge. I can't with the first mod move the soap to test the mods and second, I can't configure the game with the second mod to make it more difficult, any help?

**Comment by AGO061** [comment]
if you are playing with BRML 2.X this is normal, as stated in the first line of the "Avaliable Mods" section.

**Comment by superrrrrr** [comment]
and how could I fix it?
