### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by JasonBreen** [AGO061/BuckshotRouletteModLoader#16]
Ive been trying to install the mod loader, and i keep getting this error:
![Screenshot 2024-06-09 215349](https://github.com/AGO061/BuckshotRouletteModLoader/assets/3111341/144a347a-3b92-4f95-b908-b337720f2816)
Tried exiting steam, nothing is working

**Comment by MSLaFaver** [comment]
Sorry you're having this issue. Can you use command prompt to run your Buckshot Roulette.exe file and tell me what version and hotfix you are using? In the meantime, you can use the Delta Patcher tool (search online) to manually apply the patch. Make sure you copy the .exe to a separate folder.
