### ISSUE TITLE
Failed to patch the Steam version of the game on Linux

### ISSUE THREAD

**Issue by programneer** [AGO061/BuckshotRouletteModLoader#17]
OS: Arch Linux 6.9.3-arch1

I tried to patch the game using `brml2_linux.xdelta` file, but all i get is the checksum invalid error.
When i tried to force-patch it with `-n` option (which disables checksum validation system), and run there, i get `segmentation fault` error (printed in the terminal).
And yes i'm using legitimate copy.
Not sure if it's for itch.io or Steam version, but i think it was most likely based on itch.io one.

**Comment by programneer** [comment]
Also, you could name `brml2_steam_linux.xdelta` to prevent the confusion between itch.io and Steam versions.

**Comment by MSLaFaver** [comment]
Since there is no official Steam version for Linux, the patch only applies to the official Linux release, which is from itch.io. Unless there is a Linux Steam release that I am unaware of, you will need to use the standard xdelta patch to mod your game before porting it to Linux.

**Comment by programneer** [comment]
It is.

**Comment by MSLaFaver** [comment]
How did you install this? Can you show me the process Steam used to install the game on Linux? The store page says it's only for Windows.

**Comment by programneer** [comment]
How about the screenshot of this SteamDB depot?
![steam_linux](https://github.com/AGO061/BuckshotRouletteModLoader/assets/132811907/05329b58-6556-4f20-be12-39bcd9ceeab9)

**Comment by programneer** [comment]
I installed that way (without Proton).

**Comment by MSLaFaver** [comment]
That's strange, I had no idea there was a Steam Linux version available. In that case, BRML does not currently support your version. If you want to share your game file, I can create a temporary patch for you. You can message me at mslafaver on Discord.

**Comment by danknil** [comment]
> How did you install this? Can you show me the process Steam used to install the game on Linux? The store page says it's only for Windows.

Nope. 
![image](https://github.com/AGO061/BuckshotRouletteModLoader/assets/65212334/3503c2d4-24b5-4d25-8953-378f5683efcc)
im having same problem as OP, can you share patch file here(if he dm'ed you, otherwise i can provide game files)?

**Comment by Gamecat178** [comment]
+1 here, i am on the same train.

**Comment by Freeman-from-Space** [comment]
Same problem here with Steam Deck. I really would love to use this mod.

**Comment by mortifiedtux** [comment]
<s>I'm closing here as not only it was no longer active, but also i refunded the game a long time ago for one reason, i had enough knowledge for that, even when the multiplayer was came out, i have no interest at playing it.</s>

**Comment by mortifiedtux** [comment]
I'm here again, this time, i bought them again when i still have some spare money for some experimentals.
