### ISSUE TITLE
Multi-Language Support

### ISSUE THREAD

**Issue by Aruvelut-123** [AGO061/BuckshotRouletteModLoader#20]
Will you guys support more language like chinese?
And also can you guys give us someway to install this cause the server is hard to access in china.
Sorry for my bad english.

**Comment by Aruvelut-123** [comment]
Also you may can make a version of a installer that contains xdelta patch file in it so that our chinese players can easily install it

**Comment by MSLaFaver** [comment]
I'd be open to supporting Chinese! Could would you be able to translate anything not auto-translated by the game into Chinese and list them here? And yes, I'll make an offline installer sometime soon!

As far as the server goes, you can download and run brml3_server to host your own server.

**Comment by Aruvelut-123** [comment]
Everything in game that add by brml are not translated, i will list them here as soon as possible.
Thanks for your support!

**Comment by Aruvelut-123** [comment]
These are untranslated texts and the right is the text that translated by me.

- English | Chinese
- MODS | 模组
- LIST OF INSTALLED MODS | 模组列表
- MODLOADER - BY ... | 模组加载器 - 作者：...
- If you see this mod, it means that you patched the game correctly. To view documentation for the project this modloader is based on, see GitHub.com/GodotModding/godot-mod-loader. Thanks to ITR13 for troubleshooting and code fixes. | 如果你看见了此模组，那便意味着你正确的修补了游戏文件。想要查看此模组加载器基于的项目的文档，可前往 GitHub.com/GodotModding/godot-mod-loader。感谢 ITR13 帮助测试和修复代码。
- MODLOADER CONFIG | 模组加载器设置
- MULTIPLAYER URL | 多人服务器地址
- USERNAME | 游戏名

Those are the stuff that i seen in the game with brml installed that are not translated! Maybe there are other text but i haven't find them. Anyways, thanks for making this mod loader. It's so amazing!

**Comment by Aruvelut-123** [comment]
Also i don't know if this is bug of brml or the game, but i just check the singleplayer and see this.
![image](https://github.com/user-attachments/assets/34643383-7021-4d09-bdcc-3eda6f152016)
I haven't played singleplayer on original version of game for so long so i don't know if it's bug or game's bug.
Please check this out too.

**Comment by MSLaFaver** [comment]
Thank you so much for the translations!! I'll put these into the next version of the modloader.

I've looked into that visual issue before, and I think it is in the base game.

**Comment by MSLaFaver** [comment]
Chinese language support is added in the latest BRML version! For the installer, I would recommend downloading Delta Patcher and doing it that way.
