### ISSUE TITLE
is there a way to pr?

### ISSUE THREAD

**Issue by SirGamers** [AGO061/BuckshotRouletteModLoader#21]
i know that its an xdelta patch but cant you have the modified scripts in the actual repo so we the people can help? or is it because the modified scripts still have a part of the normal scripts and you dont wanna get in trouble with mike/critical reflex

**Comment by MSLaFaver** [comment]
Yeah there's still a significant portion of the original scripts in there. I'd suggest decompiling the modified exe if you want to help. Is there a change you'd like to make?

**Comment by SirGamers** [comment]
nah i was just wondering cuz i kinda wanted see how it all ticked and maybe modify it but ok
