### ISSUE TITLE
BRML-server does not support more than 4 active clients

### ISSUE THREAD

**Issue by XO6bl4** [AGO061/BuckshotRouletteModLoader#22]
I am currently trying to expand multiplayer, so it supports up to 6 players. Currently it doesnt allow to connect to a lobby for 5th+ client (not 5th+ player in lobby!). I opened 5 clients on my PC and it connects exactly first 4 opened clients. I tried it with a friend and he couldnt connect as 5th client to a server. It looks like the server only accepts first 4 clients. Is there any way to increase the connection limit for it?

**Comment by MSLaFaver** [comment]
This is a mistake on my part, I had previously set the client limit to 4 when doing testing on the server. I'll be increasing the limit in the future, as well as hopefully sharing the code for the server executable.

In the meantime, you can probably use GDRE Tools to edit the server code and re-export. It uses Godot v4.2.2.

**Comment by MSLaFaver** [comment]
This is fixed in the latest version!
