### ISSUE TITLE
Steam support

### ISSUE THREAD

**Issue by LukaTV939** [AGO061/BuckshotRouletteModLoader#24]
Personally I don't like how the modloader is seperate from steam version because:
- the saves are seperate
- multiplayer is now even more complicated to play with (because it's also seperate)
- the game feels much slower than the original
- there's no way steam achievements work when copying the modded version to the folder where the steam version is

I only want to use 1 QoL mod, which shows the cursor at all times, but I gotta compromise all of these things just to use it which I find really dumb

**Comment by MSLaFaver** [comment]
- You can copy saves from the Steam version to BRML.
- Using BRML with Steam multiplayer would result in wide-scale cheating and also alienate the itch.io community even more.
- Not sure what you mean by the game "feeling" slower. If you're talking about load times between scenes, that's not going to affect your gameplay.
- That's literally the point. We're not going to make something that allows cheating with Steam achievements.

It's more than possible to use your QoL mod without BRML, but you didn't ask about that before making this post. How about you do a little more work asking why things are the way they are before saying they feel dumb?
