### ISSUE TITLE
I thought heaven was fixed

### ISSUE THREAD

**Issue by zandereal1** [AGO061/BuckshotRouletteModLoader#25]
i died in the third round, nothing showed up so i checked cmd and the heaven scene was not found. (i use opengl3)

**Comment by MSLaFaver** [comment]
It should be fixed... I tested it myself and thought it was working. Are you using version 3.0.2 of the modloader?

**Comment by MSLaFaver** [comment]
It's fixed now! You can reinstall the modloader.
