### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by jhwang321** [AGO061/BuckshotRouletteModLoader#28]
Potential duplicate of a previous issue

Installation not working, on either the installer or delta patcher on windows.

Tried with "run as admin" to no avail.

![image](https://github.com/user-attachments/assets/71aaeced-f8d1-4818-8c74-1c07a2fd9d2d)
![image](https://github.com/user-attachments/assets/1615b047-b57c-4b25-b6c0-c0fdf3d0101a)

Buckshot roulette got a patch recently, could this be because of that?

**Comment by MSLaFaver** [comment]
BRML has not been updated to the latest version yet. You're likely running v2.1.0.10, which we have not said we support yet.

**Comment by jhwang321** [comment]
Thanks - I'll keep a lookout for if yall do update it!
