### ISSUE TITLE
Is there anyway to help ?

### ISSUE THREAD

**Issue by Squix** [AGO061/BuckshotRouletteModLoader#29]
As I understand, you coded this by :

1. decompiling the game
2. adding the godot-mod-loader
3. fixing bugs
4. creating a patch

I understand you have limited time. Is there a way for you to share everything you fixed at step 3 ?
I would like to work on an update for 2.1.0.

**Comment by MSLaFaver** [comment]
I'll get it out today. There's not really an easy way to share the code.
