### ISSUE TITLE
BRML V1.1.0 Prerelease has music stop playing after a bit of gameplay

### ISSUE THREAD

**Issue by EmK530** [AGO061/BuckshotRouletteModLoader#3]
Noticed this after testing my resolution mod and this also happened with no mods applied.
My best guess is something about music looping fails.
Not sure if BRML V1.0.0 is safe and frankly I'm too tired to try right now.

**Comment by AGO061** [comment]
Hi, this is a known issue that has been listed under the "Known Issues" section of the README.md file. The issue will be resolved in v1.1.0 (Pre-release 2)

**Comment by EmK530** [comment]
Ah my bad, didn't see that
