### ISSUE TITLE
Unable to play multiplayer

### ISSUE THREAD

**Issue by Ghost01900** [AGO061/BuckshotRouletteModLoader#32]
After installing this software, use steam to open the option of not displaying the module, if you open the installed version, you cannot play multiplayer, and there is no response when you click the Host table button

**Comment by D4aku** [comment]
This probably is due to [GodotSteam](https://github.com/GodotSteam/GodotSteam) not working anymore after unpacking and repacking the Godot game.

**Comment by D4aku** [comment]
Guess this can be closed then.
