### ISSUE TITLE
Error-Can't open project: No main scene defined

### ISSUE THREAD

**Issue by Akshit409** [AGO061/BuckshotRouletteModLoader#5]
Whenever I try to open the Buckshot Roulette executable (after patching it through BRML.xdelta) it shows an error "Can't open project: No main scene defined" please help me

**Comment by AGO061** [comment]
> re-download buckshot roulette and patch again, check if that works

There are 2 v1.1 versions and the latest one on itch is the one that you need.

Again, no support if the version you have is pirated.

If the issue persists you can reopen it.
