### ISSUE TITLE
Modding trouble

### ISSUE THREAD

**Issue by EmK530** [AGO061/BuckshotRouletteModLoader#6]
I'm trying to use script extensions to modify pieces of code.
My only problem right now is that I want to make changes to IntroManager.SelectedPill but almost all changes crash the game on startup.
I have a script for IntroManager which does load properly from mod_main.gd and I can tell because I was able to modify MainBathroomStart.

The thing is adding something as simple as a print line into SelectedPill or trying to change the property of something like animator_pp just crashes the game on startup.

Execution ends after this console line:
`SUCCESS ModLoader: DONE: Completely finished loading mods`

Am I doing something wrong?

**Comment by AGO061** [comment]
do you get no other output after that? Not even an error? If the console closes, try running the game via CMD, that shouldn't close.

**Comment by EmK530** [comment]
radio silence, I am running via cmd

**Comment by AGO061** [comment]
that's odd, may i see the script you are using? I mean normally it wouldn't cause a crash unless something is going terribly wrong so that's very odd

**Comment by EmK530** [comment]
Testing again, for some reason now I am able to edit things again.
I'll post if something goes wrong again, if it doesn't then I'll close this.
