### ISSUE TITLE
Grey screen when launching the game

### ISSUE THREAD

**Issue by Kenaki02** [AGO061/BuckshotRouletteModLoader#7]
Soo my game works fine when i start it without any patch, when i apply the patch and create mods folder and put a mod in it as stated in the tutorial, the game launches but i see godot logo and then grey screen with my mouse cursor only, ill share some screenshots to provide more information on whats happening, i posted on reddit and was suggested to post here soo here i am
![1](https://github.com/AGO061/BuckshotRouletteModLoader/assets/162672250/601fe714-040f-47ec-89b3-cd773dd26bdd)
![2](https://github.com/AGO061/BuckshotRouletteModLoader/assets/162672250/ddc4eb10-611a-4dea-b38a-06791366aaab)
also i got this game from my friend, idk if he bought the game or just downloaded a cracked copy he just told me he has the game and i said alr and he sent it to me, the opengl3 version works in my pc since it do not support vulkun but the blood stain effect is just annoying, should i try buying the game myself and try it then?

**Comment by AGO061** [comment]
@Kenaki02 Definitely should buy the game, maybe Mike updated it while I wasn't looking? That's weird though. Could you tell me the command you used to start the game and the console output?

**Comment by Kenaki02** [comment]
I have created a shortcut on discord and this is its path, with the command added, i tried with bat file the notepad thing also didint work still gray screen
("D:\Buckshot Roulette v1.1\Buckshot Roulette\Buckshot Roulette.exe" --rendering-driver opengl3 -cm)

**Comment by Kenaki02** [comment]
i dont know if i should buy the game or not, since its coming on steam soon here check this out (https://store.steampowered.com/app/2835570/Buckshot_Roulette/) u can just go to steam and search buckshot roulette its the same game, what happens if i buy on itchio and it launches on steam?

**Comment by AGO061** [comment]
I don't know about the itch version.
But you didn't send me the game's console output, i need to see what the errors are. Just run it via cmd and send screenshots or text of the output

**Comment by Kenaki02** [comment]
uh can u explain how to do all that? am sorry idk what ur talking abt, tell me in steps ill do as u say

**Comment by AGO061** [comment]
Open the CMD
CD to the folder where there is BR `CD "C:/Path/To/BR"`
then run BR by using the command to launch the game trough the console `"Buckshot Roulette.exe"` for example.

**Comment by Kenaki02** [comment]
so done it, instead of launching the exe i launched the opengl bat file i created like it launches the game with opengl since vulkun has error like its not supported soo like everyone else i used a bat file to launch a game and it works without the patch, ill share what the bat file is in the ss as well and after applying the patch i ran the game from the same bat file but this time i ran it from command prompt as u said and it shows the following things
![Capture](https://github.com/AGO061/BuckshotRouletteModLoader/assets/162672250/7288ed6e-080e-4439-93c4-31c08fdfd0f9)
![Capture2](https://github.com/AGO061/BuckshotRouletteModLoader/assets/162672250/36bc2c21-4edd-4943-a2af-626bfd66f260)
![Capture3](https://github.com/AGO061/BuckshotRouletteModLoader/assets/162672250/1abd7192-7b18-4e45-a940-7821fbc337fd)

**Comment by AGO061** [comment]
well from what i  can see there are errors before Godot even prints the engine version. I'm clueless, really. Have you tried re-patching?

**Comment by Kenaki02** [comment]
hm let me do it

**Comment by Kenaki02** [comment]
an update i wanted to give, nothing worked, soo the simplest solution i found was to download an emulator and use the android port of the game, it had a few bugs but atleast was playable, and i confirmed from my friend he did buy the game it was the original copy

**Comment by AGO061** [comment]
odd, nothing i did ever caused issues, this is a weird bug. I'll close this for now.

**Comment by Kenaki02** [comment]
sure
