### ISSUE TITLE
About the version 1.2 update

### ISSUE THREAD

**Issue by MadestSamurai** [AGO061/BuckshotRouletteModLoader#8]
The game has been updated to version 1.2 in recent days (on Steam) and the OpenGL rendering issues are still there (including blood, DEALER's text, etc.), and I would like to ask if you have any plans to update the modder plug-in that corresponds to version 1.2?

**Comment by AGO061** [comment]
BRML 2.0 should be pushed out today for the steam version, but old mods
might not be compatible (the opengl3 fix does not work for example) but
another user is working on an xdelta for opengl3 almost perfect support

Il lun 8 apr 2024, 04:51 David Dai ***@***.***> ha scritto:

**Comment by MadestSamurai** [comment]
The game developers did a patch for OpenGL3 and now there are no blood spatter or text bugs. However, the game rooms are a bit bright (I guess the lighting shadows are not rendered) and the blood spatter has been removed outright.

**Comment by AGO061** [comment]
the user i was talking about made the mod, and it made it into the official version. as for the shadows, opengl3 in Godot 4.1 doesn't support them.
