### ISSUE TITLE
Can't use opengl3

### ISSUE THREAD

**Issue by Bodyawad93** [AGO061/BuckshotRouletteModLoader#9]
whenever i put the --rendering-driver opengl3 it still doesnt work and gives me the error please fix

**Comment by MSLaFaver** [comment]
Did you put `-cm` on the end as well?

**Comment by Bodyawad93** [comment]
also im putting the command inside the shortcut that is already made when u install brml aka the desktop shortcut is that how you do it or am i doing it wrong

**Comment by MSLaFaver** [comment]
That is not how you do it. Please reread the "Troubleshooting" section to learn how to edit the brml.bat file, not the shortcut.

**Comment by Bodyawad93** [comment]
> That is not how you do it. Please reread the "Troubleshooting" section to learn how to edit the brml.bat file, not the shortcut.

oh where is the troubleshooting section?

**Comment by Bodyawad93** [comment]
> > That is not how you do it. Please reread the "Troubleshooting" section to learn how to edit the brml.bat file, not the shortcut.
> 
> oh where is the troubleshooting section?

nvm i found it sorry im dumb gonna try that now

**Comment by Bodyawad93** [comment]
works tysm
